Flatten json
MobilityNet/mobilitynet-analysis-scripts pull request #57
Opened 2021-04-23 15:04 UTC by singhish

2021-04-25 00:01 UTC, shankari requested changes
In the new notebook, I don't see the code equivalent to the code in the original that iterates over the phone view and eval view.
I'm referring in particular to cells 9 and 11 in the original template. How can we show the trips/sections and experiments with the new flattened structures?

2021-04-25 00:23 UTC, shankari requested changes
At another high level, your current code examples don't seem to meet pandas guidelines.
In general, you don't want to iterate over the rows of a dataframe because it doesn't use the cython/numpy optimizations and has to run in python.

If there is a reason why you need to iterate over dataframe rows, can you explain the reason in the documentation? Again, this is the first notebook that most people will access to understand the data, and it needs to set a good template for the other notebooks.

2021-04-25 00:23 UTC, shankari commented on Data_exploration_template_tabular.ipynb
> +    "        print(\"Has valid `ts` values for each section range ✅ \")"
example of itertuples

2021-04-25 00:23 UTC, shankari commented on Data_exploration_template_tabular.ipynb
> +   ]
Ditto

2021-04-25 00:23 UTC, shankari commented on Data_exploration_template_tabular.ipynb
> +    "sr_subset = [\"trip_range_id_base\", \"section_range_gt_start_ts\", \"section_range_gt_end_ts\"]\n",
why is this using the `trip_range_id_base` instead of a `section_range_id`?

2021-04-25 00:23 UTC, shankari commented on Data_exploration_template_tabular.ipynb
> +    "        third_rep.plot(ax=ax, x=\"hr\", y=\"battery_level_pct\", label=f\"{phone_label} ({role})\", ylim=(0, 100))"
Here's another enumerate call.

2021-04-25 00:27 UTC, shankari commented
Note also that line 364 of the Data exploration template is currently broken because it calls `get_ground_truth_for_leg` without start and end timestamps. I am not sure how this ever worked after
https://github.com/MobilityNet/mobilitynet-analysis-scripts/commit/62fe20fc24353c2b68918043000164a82fad4f49

Did you not test https://github.com/MobilityNet/mobilitynet-analysis-scripts/pull/56 with all the notebooks?

2021-04-30 20:32 UTC, singhish commented
@shankari I don't think I ever got around to verifying this.

2022-11-28 06:08 UTC, shankari commented
subsumed by https://github.com/MobilityNet/mobilitynet-analysis-scripts/pull/60

2022-11-28 06:08 UTC, closed without merging

2022-11-28 06:10 UTC, shankari commented
<img width="740" alt="Screen Shot 2022-11-27 at 10 10 24 PM" src="https://user-images.githubusercontent.com/2423263/204206149-9056bcc6-a40d-440e-b6d8-e2260659ecc1.png">

2022-11-28 06:12 UTC, shankari commented
<img width="740" alt="Screen Shot 2022-11-27 at 10 11 56 PM" src="https://user-images.githubusercontent.com/2423263/204206312-11a20474-eb4c-44c7-83f1-6df106ec9982.png">